# Generated by Django 3.2.6 on 2021-08-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('url_to_image', models.URLField()),
                ('published_at', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('articles', models.ManyToManyField(to='main.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ManyToManyField(to='main.Source'),
        ),
    ]
